---
- name: Deploy dummy application
  hosts: app
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: https://github.com/ltblueberry/dummy-node-mongo.git
        dest: /home/appuser/app
        version: master

    - name: Install packages based on package.json.
      npm:
        path: /home/appuser/app
      notify: restart dummy

  handlers:
  - name: restart dummy
    become: true
    systemd: 
      name: dummy
      state: restarted